name: 'dbt_observability'
version: '1.3.5'
config-version: 2
require-dbt-version: ">=1.3.0"
profile: "dbt_observability"

clean-targets: # folders to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "logs"

models:
  dbt_observability:
    +materialized: table
    +file_format: delta
    +schema: observability
    sources:
      +materialized: incremental
      +on_schema_change: append_new_columns
      +full_refresh: false
    +access: public
    staging:
      +schema: observability
      +materialized: view
    views:
      +schema: observability
      +materialized: view

dispatch:
  - macro_namespace: dbt
    search_order: ['dbt_observability', 'dbt']
  - macro_namespace: dbt_utils
    search_order: ['dbt_observability', 'dbt_utils']
