version: 2
dbt_observability:
  models:
  - name: sources
    description: Dimension model that contains data about sources.
    columns:
    - name: command_invocation_id
      description: '{{ doc("command_invocation_id") }}'
    - name: node_id
      description: '{{ doc("node_id") }}'
    - name: run_started_at
      description: '{{ doc("run_started_at") }}'
    - name: database_name
      description: '{{ doc("database_name") }}'
    - name: schema_name
      description: '{{ doc("schema_name") }}'
    - name: source_name
      description: '{{ doc("source_name") }}'
    - name: loader
      description: '{{ doc("loader") }}'
    - name: name
      description: '{{ doc("name") }}'
    - name: identifier
      description: '{{ doc("identifier") }}'
    - name: loaded_at_field
      description: '{{ doc("loaded_at_field") }}'
    - name: freshness
      description: '{{ doc("freshness") }}'
    - name: total_rowcount
      description: '{{ doc("total_rowcount") }}'
